theme: jekyll-theme-cayman
<!DOCTYPE html>
<html><head>
<title>Hello World!</title>
</head><body>
<h1>Hello World!</h1>
<p>欢迎来到Liuxuanmo的网站</p>
</body></html>
<meta charset="UTF-8">
<title></title>
<style>
body{margin:0;padding:60px;background-color:#eee;font-size:30px;}
div,p{margin:0;padding:0;}
h1{margin:0;padding:0 0 8px;font-family:"微软雅黑","黑体";}
.txt{color:#999;margin:0;padding:0 0 8px;font-family:"微软雅黑","黑体";}
.divbox{width:60%;margin:0 auto;padding:30px 42px;background-color:#fff;box-shadow:2px 2px 3px rgba(0, 0, 0, 0.16);border:1px solid #9a9a9a;}
.divbox p{padding:5px;font-size:16px;font-family:"Tahoma";}
.divbox p.gap{height:60px;}
</style>
</head>
